# Generated by Django 3.2.9 on 2021-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211119_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
